### ISSUE TITLE
RevisionSyntaxException on "a  b"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ngocanh7948github/gitiles#18]
```
GET 
android.googlesource.com/platform/packages/apps/Launcher/+/1dd3a077a293bf3ac%20%
204e61e91dcc3dfc99487acd4/res/values/dimens.xml

org.eclipse.jgit.errors.RevisionSyntaxException:1dd3a077a293bf3ac  
4e61e91dcc3dfc99487acd4
    at org.eclipse.jgit.lib.Repository.resolve(Repository.java:706)
    at org.eclipse.jgit.lib.Repository.resolve(Repository.java:385)
    at com.google.gitiles.RevisionParser.parse(RevisionParser.java:171)
    at com.google.gitiles.ViewFilter.parse(ViewFilter.java:116)
    at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:79)
    at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
    at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:33)

If the revision syntax expression is wrong the client should be given an error 
page under a 4xx status code and not an HTTP 500. A malformed request parameter 
should not cause a 500.
```

Original issue reported on code.google.com by `sop@google.com` on 6 Jan 2013 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
Here is another similar sort of failure:

gerrit.googlesource.com/gerrit/+/master%5E2/INSTALL
org.eclipse.jgit.errors.RevisionSyntaxException:master^2/INSTALL
    at org.eclipse.jgit.lib.Repository.resolve(Repository.java:706)
    at org.eclipse.jgit.lib.Repository.resolve(Repository.java:385)
    at com.google.gitiles.RevisionParser.parse(RevisionParser.java:171)
    at com.google.gitiles.ViewFilter.parse(ViewFilter.java:116)
    at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:79)
    at com.google.gitiles.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
    at com.google.gitiles.ViewFilter.doFilter(ViewFilter.java:33)

Asking for the 2nd parent of a non-merge should not cause an HTTP 500.
```

Original comment by `sop@google.com` on 6 Jan 2013 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 
https://gerrit.googlesource.com/gitiles/+/44a158445e6082b3a1778a2f6333167432d9ba
e5%5E
```

Original comment by `dborowitz@google.com` on 7 Jan 2013 at 9:22
- Changed state: **Fixed**
