### ISSUE TITLE
Gerrit is crashing trying to render a markdown page (I think)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ngocanh7948github/gitiles#75]
```
Go to:

https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/reference.
md

and get a 500 server error.

This file is probably quite large, and it's entirely possible that there's some 
bad markdown in it somewhere ...
```

Original issue reported on code.google.com by `dpranke@chromium.org` on 18 Apr 2015 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
Okay, it looks like the [TOC] directive is choking on multiple headers with the 
same text. I'll temporarily land a fix that disables the TOC ...
```

Original comment by `dpranke@chromium.org` on 18 Apr 2015 at 12:13

**Comment by GoogleCodeExporter** [comment]
```
Unexpected exception caught during GET 
chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/reference.md
java.lang.IllegalArgumentException: value already present: Examples-cd0f7cff
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:236)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:213)
    at com.google.gitiles.doc.TocFormatter.idFromHeader(TocFormatter.java:76)
    at com.google.gitiles.doc.TocFormatter.outline(TocFormatter.java:117)
    at com.google.gitiles.doc.TocFormatter.outline(TocFormatter.java:104)
    at com.google.gitiles.doc.TocFormatter.outline(TocFormatter.java:107)
    at com.google.gitiles.doc.TocFormatter.format(TocFormatter.java:94)
    at com.google.gitiles.doc.MarkdownToHtml.visit(MarkdownToHtml.java:115)
    at com.google.gitiles.doc.TocNode.accept(TocNode.java:27)
    at com.google.gitiles.doc.MarkdownToHtml.visitChildren(MarkdownToHtml.java:522)
    at com.google.gitiles.doc.MarkdownToHtml.visit(MarkdownToHtml.java:110)
    at org.pegdown.ast.RootNode.accept(RootNode.java:51)
    at com.google.gitiles.doc.MarkdownToHtml.toSoyHtml(MarkdownToHtml.java:103)
    at com.google.gitiles.doc.DocServlet.showDoc(DocServlet.java:187)
    at com.google.gitiles.doc.DocServlet.doGetHtml(DocServlet.java:141)
    at com.google.gitiles.BaseServlet.doGet(BaseServlet.java:117)
```

Original comment by `jrn@google.com` on 18 Apr 2015 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
I guess this is probably a bug in gitiles, not gerrit; I'll re-file it there.
```

Original comment by `dpranke@chromium.org` on 21 Jun 2015 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
https://gerrit-review.googlesource.com/68871
```

Original comment by `sop@google.com` on 22 Jun 2015 at 9:25
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sop@google.com` on 24 Jun 2015 at 5:37
- Changed state: **Fixed**
